version: 2.1


jobs:
  preview_deployment:
    docker:
      - image: circleci/node:latest
    environment:
      VERCEL_ORG_ID: $VERCEL_ORG_ID
      VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: sudo npm install -g vercel
      - run:
          name: Debug Environment Variables
          command: |
            echo "VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID"
            echo "VERCEL_ORG_ID: $VERCEL_ORG_ID"
            echo "VERCEL_TOKEN: $VERCEL_TOKEN"
      - run:
          name: Pull Vercel Environment Information
          command: vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
      - run:
          name: Build Project Artifacts
          command: vercel build --token=$VERCEL_TOKEN
      - run:
          name: Deploy Project Artifacts to Vercel
          command: vercel deploy --prebuilt --token=$VERCEL_TOKEN

  production_deployment:
    docker:
      - image: circleci/node:latest    
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: sudo npm install -g vercel
      - run:
          name: Debug Environment Variables
          command: |
            echo "VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID"
            echo "VERCEL_ORG_ID: $VERCEL_ORG_ID"
            echo "VERCEL_TOKEN: $VERCEL_TOKEN"
            echo "VAGGELIS_SECRET_MESSAGE: $VAGGELIS_SECRET_MESSAGE"
      - run:
          name: Pull Vercel Environment Information
          command: vercel pull --yes --environment=production --token=$VERCEL_TOKEN
      - run:
          name: Build Project Artifacts
          command: vercel build --prod --token=$VERCEL_TOKEN
      - run:
          name: Deploy Project Artifacts to Vercel
          command: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

workflows:
  version: 2
  preview_and_production:
    jobs:
      - preview_deployment:
          filters:
            branches:
              ignore: /main/
      - production_deployment:
          filters:
            branches:
              only: /main/